name: Deploy Privacy Policy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'PRIVACY_POLICY.md'
      - '.github/workflows/deploy-privacy-policy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install -g markdown-to-html
        
      - name: Convert Markdown to HTML
        run: |
          markdown-to-html PRIVACY_POLICY.md > index.html
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages 